[rospy.client][INFO] 2017-10-04 16:41:48,679: init_node, name[/threshold_sender], pid[4435]
[xmlrpc][INFO] 2017-10-04 16:41:48,679: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-10-04 16:41:48,679: Started XML-RPC server [http://ubuntu:40562/]
[rospy.init][INFO] 2017-10-04 16:41:48,680: ROS Slave URI: [http://ubuntu:40562/]
[rospy.impl.masterslave][INFO] 2017-10-04 16:41:48,680: _ready: http://ubuntu:40562/
[xmlrpc][INFO] 2017-10-04 16:41:48,680: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-10-04 16:41:48,680: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-10-04 16:41:48,780: registered with master
[rospy.rosout][INFO] 2017-10-04 16:41:48,781: initializing /rosout core topic
[rospy.rosout][INFO] 2017-10-04 16:41:48,784: connected to core topic /rosout
[rospy.simtime][INFO] 2017-10-04 16:41:48,785: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-10-04 16:41:49,014: topic[/camera/image_raw/theora/parameter_descriptions] adding connection to [http://ubuntu:38650/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,085: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,116: topic[/image/compressedDepth/parameter_descriptions] adding connection to [http://ubuntu:45756/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,141: topic[/image/marked/compressedDepth/parameter_descriptions] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,226: topic[/image/theora/parameter_descriptions] adding connection to [http://ubuntu:45756/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,237: topic[/image_marked/compressed/parameter_updates] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,251: topic[/view/parameter_descriptions] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,265: topic[/view/parameter_updates] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,266: topic[/mask_orange/parameter_updates] adding connection to [http://ubuntu:45756/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,270: topic[/image_marked/theora/parameter_updates] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,280: topic[/mask_orange/parameter_descriptions] adding connection to [http://ubuntu:45756/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,290: topic[/image_marked/compressedDepth/parameter_updates] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,302: topic[/image_marked/theora/parameter_descriptions] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,305: topic[/image_marked/compressed/parameter_descriptions] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,312: topic[/image/marked/theora/parameter_updates] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,319: topic[/image_marked/compressedDepth/parameter_descriptions] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,320: topic[/image/theora/parameter_updates] adding connection to [http://ubuntu:45756/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,330: topic[/image/marked/theora/parameter_descriptions] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,335: topic[/image/marked/compressed/parameter_updates] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,338: topic[/image/marked/compressedDepth/parameter_updates] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,341: topic[/image/marked/compressed/parameter_descriptions] adding connection to [http://ubuntu:45195/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,347: topic[/image/compressed/parameter_updates] adding connection to [http://ubuntu:45756/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,350: topic[/image/compressedDepth/parameter_updates] adding connection to [http://ubuntu:45756/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,352: topic[/image/compressed/parameter_descriptions] adding connection to [http://ubuntu:45756/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,362: topic[/camera/image_raw/theora/parameter_updates] adding connection to [http://ubuntu:38650/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,376: topic[/camera/image_raw/compressedDepth/parameter_updates] adding connection to [http://ubuntu:38650/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,385: topic[/camera/image_raw/compressedDepth/parameter_descriptions] adding connection to [http://ubuntu:38650/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,391: topic[/camera/image_raw/compressed/parameter_updates] adding connection to [http://ubuntu:38650/], count 0
[rospy.internal][INFO] 2017-10-04 16:41:49,401: topic[/camera/image_raw/compressed/parameter_descriptions] adding connection to [http://ubuntu:38650/], count 0
[rospy.internal][INFO] 2017-10-04 17:12:52,885: topic impl's ref count is zero, deleting topic /mask_orange/parameter_descriptions...
[rospy.internal][INFO] 2017-10-04 17:12:52,893: topic[/mask_orange/parameter_descriptions] removing connection to http://ubuntu:45756/
[rospy.internal][INFO] 2017-10-04 17:12:52,895: topic impl's ref count is zero, deleting topic /mask_orange/parameter_updates...
[rospy.internal][INFO] 2017-10-04 17:12:52,896: topic[/mask_orange/parameter_updates] removing connection to http://ubuntu:45756/
[rospy.core][INFO] 2017-10-04 17:12:53,047: signal_shutdown [atexit]
[rospy.internal][INFO] 2017-10-04 17:12:53,128: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-10-04 17:12:53,129: topic[/image/marked/compressed/parameter_descriptions] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,129: topic[/camera/image_raw/theora/parameter_descriptions] removing connection to http://ubuntu:38650/
[rospy.internal][INFO] 2017-10-04 17:12:53,129: topic[/image/marked/theora/parameter_descriptions] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,130: topic[/image_marked/theora/parameter_descriptions] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,130: topic[/image/compressedDepth/parameter_updates] removing connection to http://ubuntu:45756/
[rospy.internal][INFO] 2017-10-04 17:12:53,134: topic[/image/theora/parameter_descriptions] removing connection to http://ubuntu:45756/
[rospy.internal][INFO] 2017-10-04 17:12:53,135: topic[/image_marked/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,152: topic[/image_marked/compressed/parameter_updates] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,156: topic[/camera/image_raw/compressed/parameter_descriptions] removing connection to http://ubuntu:38650/
[rospy.internal][WARNING] 2017-10-04 17:12:53,176: Unknown error initiating TCP/IP socket to ubuntu:37436 (http://ubuntu:38650/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-10-04 17:12:53,180: topic[/image_marked/compressedDepth/parameter_updates] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,184: topic[/image/compressed/parameter_descriptions] removing connection to http://ubuntu:45756/
[rospy.internal][INFO] 2017-10-04 17:12:53,185: topic[/image/marked/theora/parameter_updates] removing connection to http://ubuntu:45195/
[rospy.internal][WARNING] 2017-10-04 17:12:53,185: Unknown error initiating TCP/IP socket to ubuntu:58714 (http://ubuntu:45756/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-10-04 17:12:53,185: topic[/image/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:45756/
[rospy.internal][INFO] 2017-10-04 17:12:53,188: topic[/image/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:45756/
[rospy.topics][ERROR] 2017-10-04 17:12:53,192: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-04 17:12:53,193: topic[/image/marked/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:45195/
[rospy.internal][WARNING] 2017-10-04 17:12:53,193: Unknown error initiating TCP/IP socket to ubuntu:37436 (http://ubuntu:38650/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-10-04 17:12:53,193: topic[/camera/image_raw/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:38650/
[rospy.internal][INFO] 2017-10-04 17:12:53,193: topic[/camera/image_raw/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:38650/
[rospy.topics][ERROR] 2017-10-04 17:12:53,193: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][WARNING] 2017-10-04 17:12:53,193: Unknown error initiating TCP/IP socket to ubuntu:37436 (http://ubuntu:38650/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-10-04 17:12:53,193: topic[/camera/image_raw/compressedDepth/parameter_updates] removing connection to http://ubuntu:38650/
[rospy.internal][INFO] 2017-10-04 17:12:53,194: topic[/camera/image_raw/compressedDepth/parameter_updates] removing connection to http://ubuntu:38650/
[rospy.topics][ERROR] 2017-10-04 17:12:53,194: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-04 17:12:53,194: topic[/camera/image_raw/theora/parameter_updates] removing connection to http://ubuntu:38650/
[rospy.internal][WARNING] 2017-10-04 17:12:53,202: Unknown error initiating TCP/IP socket to ubuntu:37436 (http://ubuntu:38650/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-10-04 17:12:53,202: topic[/camera/image_raw/compressed/parameter_updates] removing connection to http://ubuntu:38650/
[rospy.internal][INFO] 2017-10-04 17:12:53,202: topic[/camera/image_raw/compressed/parameter_updates] removing connection to http://ubuntu:38650/
[rospy.topics][ERROR] 2017-10-04 17:12:53,202: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-10-04 17:12:53,202: topic[/view/parameter_updates] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,203: topic[/image_marked/theora/parameter_updates] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,205: topic[/image/marked/compressed/parameter_updates] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,205: topic[/image/marked/compressedDepth/parameter_updates] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,216: topic[/view/parameter_descriptions] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,216: topic[/image/compressed/parameter_updates] removing connection to http://ubuntu:45756/
[rospy.internal][INFO] 2017-10-04 17:12:53,220: topic[/image_marked/compressed/parameter_descriptions] removing connection to http://ubuntu:45195/
[rospy.internal][INFO] 2017-10-04 17:12:53,224: topic[/image/theora/parameter_updates] removing connection to http://ubuntu:45756/
[rospy.impl.masterslave][INFO] 2017-10-04 17:12:53,230: atexit
[rospy.internal][WARNING] 2017-10-04 17:12:53,274: Unknown error initiating TCP/IP socket to ubuntu:37436 (http://ubuntu:38650/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,275: Unknown error initiating TCP/IP socket to ubuntu:37436 (http://ubuntu:38650/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,358: Unknown error initiating TCP/IP socket to ubuntu:58714 (http://ubuntu:45756/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,358: Unknown error initiating TCP/IP socket to ubuntu:58714 (http://ubuntu:45756/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,358: Unknown error initiating TCP/IP socket to ubuntu:58714 (http://ubuntu:45756/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,358: Unknown error initiating TCP/IP socket to ubuntu:58714 (http://ubuntu:45756/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,359: Unknown error initiating TCP/IP socket to ubuntu:58714 (http://ubuntu:45756/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,359: Unknown error initiating TCP/IP socket to ubuntu:58714 (http://ubuntu:45756/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,359: Unknown error initiating TCP/IP socket to ubuntu:58714 (http://ubuntu:45756/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,453: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,455: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,456: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,456: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,456: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,456: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,457: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,457: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,457: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,457: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,457: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,458: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,458: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-10-04 17:12:53,460: Unknown error initiating TCP/IP socket to ubuntu:48621 (http://ubuntu:45195/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

