[rospy.client][INFO] 2017-09-26 18:45:22,402: init_node, name[/rqt_reconfigure], pid[99736]
[xmlrpc][INFO] 2017-09-26 18:45:22,404: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2017-09-26 18:45:22,405: ROS Slave URI: [http://ubuntu:34090/]
[xmlrpc][INFO] 2017-09-26 18:45:22,405: Started XML-RPC server [http://ubuntu:34090/]
[rospy.impl.masterslave][INFO] 2017-09-26 18:45:22,414: _ready: http://ubuntu:34090/
[xmlrpc][INFO] 2017-09-26 18:45:22,425: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-09-26 18:45:22,425: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-09-26 18:45:22,506: registered with master
[rospy.rosout][INFO] 2017-09-26 18:45:22,506: initializing /rosout core topic
[rospy.rosout][INFO] 2017-09-26 18:45:22,518: connected to core topic /rosout
[rospy.simtime][INFO] 2017-09-26 18:45:22,526: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-09-26 18:45:22,783: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-09-26 18:45:22,947: topic[/camera/image_raw/compressedDepth/parameter_updates] adding connection to [http://ubuntu:34896/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,092: topic[/image/compressed/parameter_descriptions] adding connection to [http://ubuntu:33604/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,276: topic[/image/compressedDepth/parameter_updates] adding connection to [http://ubuntu:33604/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,302: topic[/view/parameter_descriptions] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,312: topic[/image_marked/theora/parameter_updates] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,348: topic[/view/parameter_updates] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,353: topic[/image_marked/compressedDepth/parameter_updates] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,363: topic[/image_marked/compressedDepth/parameter_descriptions] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,367: topic[/image_marked/compressed/parameter_updates] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,379: topic[/image/theora/parameter_updates] adding connection to [http://ubuntu:33604/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,389: topic[/image/marked/theora/parameter_updates] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,395: topic[/image_marked/theora/parameter_descriptions] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,401: topic[/image/marked/compressedDepth/parameter_updates] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,406: topic[/image/marked/compressedDepth/parameter_descriptions] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,411: topic[/image_marked/compressed/parameter_descriptions] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,439: topic[/image/theora/parameter_descriptions] adding connection to [http://ubuntu:33604/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,446: topic[/image/marked/theora/parameter_descriptions] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,481: topic[/image/compressed/parameter_updates] adding connection to [http://ubuntu:33604/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,540: topic[/image/marked/compressed/parameter_updates] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,576: topic[/image/marked/compressed/parameter_descriptions] adding connection to [http://ubuntu:37987/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,610: topic[/camera/image_raw/theora/parameter_updates] adding connection to [http://ubuntu:34896/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,622: topic[/image/compressedDepth/parameter_descriptions] adding connection to [http://ubuntu:33604/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,626: topic[/camera/image_raw/theora/parameter_descriptions] adding connection to [http://ubuntu:34896/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,636: topic[/camera/image_raw/compressedDepth/parameter_descriptions] adding connection to [http://ubuntu:34896/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,672: topic[/camera/image_raw/compressed/parameter_updates] adding connection to [http://ubuntu:34896/], count 0
[rospy.internal][INFO] 2017-09-26 18:45:23,684: topic[/camera/image_raw/compressed/parameter_descriptions] adding connection to [http://ubuntu:34896/], count 0
[rospy.core][INFO] 2017-09-26 18:46:22,439: signal_shutdown [atexit]
[rospy.internal][INFO] 2017-09-26 18:46:22,551: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-09-26 18:46:22,552: topic[/image/marked/compressed/parameter_descriptions] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,553: topic[/camera/image_raw/theora/parameter_descriptions] removing connection to http://ubuntu:34896/
[rospy.internal][INFO] 2017-09-26 18:46:22,559: topic[/image/marked/theora/parameter_descriptions] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,567: topic[/image_marked/theora/parameter_descriptions] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,568: topic[/image_marked/compressed/parameter_updates] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,580: topic[/image/theora/parameter_descriptions] removing connection to http://ubuntu:33604/
[rospy.internal][INFO] 2017-09-26 18:46:22,587: topic[/image_marked/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,588: topic[/image/compressedDepth/parameter_updates] removing connection to http://ubuntu:33604/
[rospy.internal][INFO] 2017-09-26 18:46:22,588: topic[/camera/image_raw/compressed/parameter_descriptions] removing connection to http://ubuntu:34896/
[rospy.internal][INFO] 2017-09-26 18:46:22,589: topic[/image_marked/compressedDepth/parameter_updates] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,589: topic[/image/compressed/parameter_descriptions] removing connection to http://ubuntu:33604/
[rospy.internal][WARNING] 2017-09-26 18:46:22,595: Unknown error initiating TCP/IP socket to ubuntu:56823 (http://ubuntu:33604/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2017-09-26 18:46:22,595: Unknown error initiating TCP/IP socket to ubuntu:56619 (http://ubuntu:34896/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-09-26 18:46:22,596: topic[/image/marked/theora/parameter_updates] removing connection to http://ubuntu:37987/
[rospy.internal][WARNING] 2017-09-26 18:46:22,596: Unknown error initiating TCP/IP socket to ubuntu:56823 (http://ubuntu:33604/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-09-26 18:46:22,596: topic[/image/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:33604/
[rospy.internal][INFO] 2017-09-26 18:46:22,598: topic[/image/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:33604/
[rospy.topics][ERROR] 2017-09-26 18:46:22,614: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-09-26 18:46:22,625: topic[/image/marked/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:37987/
[rospy.internal][WARNING] 2017-09-26 18:46:22,626: Unknown error initiating TCP/IP socket to ubuntu:56619 (http://ubuntu:34896/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-09-26 18:46:22,626: topic[/camera/image_raw/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:34896/
[rospy.internal][INFO] 2017-09-26 18:46:22,626: topic[/camera/image_raw/compressedDepth/parameter_descriptions] removing connection to http://ubuntu:34896/
[rospy.topics][ERROR] 2017-09-26 18:46:22,626: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][WARNING] 2017-09-26 18:46:22,626: Unknown error initiating TCP/IP socket to ubuntu:56619 (http://ubuntu:34896/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-09-26 18:46:22,626: topic[/camera/image_raw/compressedDepth/parameter_updates] removing connection to http://ubuntu:34896/
[rospy.internal][INFO] 2017-09-26 18:46:22,630: topic[/camera/image_raw/compressedDepth/parameter_updates] removing connection to http://ubuntu:34896/
[rospy.topics][ERROR] 2017-09-26 18:46:22,630: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-09-26 18:46:22,630: topic[/camera/image_raw/theora/parameter_updates] removing connection to http://ubuntu:34896/
[rospy.internal][WARNING] 2017-09-26 18:46:22,631: Unknown error initiating TCP/IP socket to ubuntu:56619 (http://ubuntu:34896/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-09-26 18:46:22,631: topic[/camera/image_raw/compressed/parameter_updates] removing connection to http://ubuntu:34896/
[rospy.internal][INFO] 2017-09-26 18:46:22,631: topic[/camera/image_raw/compressed/parameter_updates] removing connection to http://ubuntu:34896/
[rospy.topics][ERROR] 2017-09-26 18:46:22,631: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-09-26 18:46:22,634: topic[/view/parameter_updates] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,635: topic[/image_marked/theora/parameter_updates] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,642: topic[/image/marked/compressed/parameter_updates] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,642: topic[/image/marked/compressedDepth/parameter_updates] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,643: topic[/view/parameter_descriptions] removing connection to http://ubuntu:37987/
[rospy.internal][WARNING] 2017-09-26 18:46:22,643: Unknown error initiating TCP/IP socket to ubuntu:56823 (http://ubuntu:33604/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2017-09-26 18:46:22,643: topic[/image/compressed/parameter_updates] removing connection to http://ubuntu:33604/
[rospy.internal][INFO] 2017-09-26 18:46:22,643: topic[/image/compressed/parameter_updates] removing connection to http://ubuntu:33604/
[rospy.topics][ERROR] 2017-09-26 18:46:22,643: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-09-26 18:46:22,644: topic[/image_marked/compressed/parameter_descriptions] removing connection to http://ubuntu:37987/
[rospy.internal][INFO] 2017-09-26 18:46:22,644: topic[/image/theora/parameter_updates] removing connection to http://ubuntu:33604/
[rospy.impl.masterslave][INFO] 2017-09-26 18:46:22,644: atexit
[rospy.internal][WARNING] 2017-09-26 18:46:22,748: Unknown error initiating TCP/IP socket to ubuntu:56619 (http://ubuntu:34896/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,748: Unknown error initiating TCP/IP socket to ubuntu:56619 (http://ubuntu:34896/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,764: Unknown error initiating TCP/IP socket to ubuntu:56823 (http://ubuntu:33604/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,765: Unknown error initiating TCP/IP socket to ubuntu:56823 (http://ubuntu:33604/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,766: Unknown error initiating TCP/IP socket to ubuntu:56823 (http://ubuntu:33604/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,871: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,871: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,871: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,872: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,872: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,872: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,872: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,873: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,873: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,873: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,873: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,873: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,873: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

[rospy.internal][WARNING] 2017-09-26 18:46:22,874: Unknown error initiating TCP/IP socket to ubuntu:51851 (http://ubuntu:37987/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] 接続が相手からリセットされました

